### ISSUE TITLE
mergeQuery: add support for "$and" and "$or"

### ISSUE THREAD

**Issue by fratzinger** [fratzinger/feathers-utils#5]

**Comment by mrfrase3** [comment]
I was literally about to post this XD

`$eq` is also not supported.

Something that I do in one of my advanced feathers implementations is when adding "security" filters, I add them to an `$and`, so that they won't conflict with the main query.

Say I have the following:
``` js
// incoming query
{
  id: { $in: [1, 2, 3] },
  status: 'complete',
}
// casl abilities query:
{
  id: { $in: [2, 3, 4] },
  status: { $in: ['complete', 'pending', 'draft'] },
}
```
I'm not sure how smart the merging logic is, but what you can just do is:
```js
{
  id: { $in: [1, 2, 3] },
  status: 'complete',
  $and: [{
    id: { $in: [2, 3, 4] },
    status: { $in: ['complete', 'pending', 'draft'] },
  }],
}
```
All you need to do is check if `$and` exists as an array, otherwise initialise it, then push the ability query to the end of it.

Not sure if this blows the scope of this ticket, let me know if you want me to make a separate one.

**Comment by fratzinger** [comment]
Thanks for your thoughts! And thanks for your well explained issue! 😃 
My initial issue with this was slightly another thing, that you sketched out.

I mostly use `mergeQuery` for `feathers-casl`, where I have added this to `feathers-casl@0.4.1.-5`. 
I needed a logic to combine `$and` and `$or`, if it exists in both queries with `handle: 'intersect'`. I have added this functionality to `feathers-utils@1.5.4`, so this issue, as I thought about it, could be closed.

Before we maybe could work a way out for your issue, let me point out a thing and let me ask a question:

**Disclaimer**: `feathers-utils` is mostly intended to be my own library, where I source out some code I need regularly. Having said this, my motivation to add support for a variety of use cases that eventually exist, is limited. If it does not overlap with my use case, there is a good chance that I need support to fix this issue.

**Question**: In which context do you use `mergeQuery` or `feathers-utils` at all? Is it in a custom `casl` hook or is it with `feathers-casl`?

**Comment by mrfrase3** [comment]
oh, sorry, just feathers-casl

on the [npm page for feathers-casl](https://www.npmjs.com/package/feathers-casl) the repo is listed as this repo, which must be incorrect. I clicked on that and came here to post the issue without giving it much thought.

I'll re-post this in that repo >.<
